### ISSUE TITLE
增加绘制图片圆角

### ISSUE THREAD

**Issue by chinbor** [1247748612/edraw#4]
![image](https://user-images.githubusercontent.com/35005731/188651491-08777786-0699-4fce-8e29-94645c18bd4e.png)
> 可以在内部增加绘制 圆角的代码

**Comment by chinbor** [comment]
本来想自己动手操作，源码存在roundPath方法，但是！！！仓库源码在本地启动不了！！！报很多错误

**Comment by Dunqing** [comment]
> 本来想自己动手操作，源码存在roundPath方法，但是！！！仓库源码在本地启动不了！！！报很多错误

可以贴下报错截图我看看是什么原因 我隔了很久没跑也遇到了报错🥲

**Comment by chinbor** [comment]
![image](https://user-images.githubusercontent.com/35005731/188656774-be6d3209-3b94-4912-a26e-65525f50269e.png)
这个应该是pnpm版本问题
![image](https://user-images.githubusercontent.com/35005731/188656861-2d8fd4c3-8c17-4bbf-b242-7f5af55e2f1a.png)
这个是代码检测问题

**Comment by chinbor** [comment]
还有就是离谱的是，扩展自己的edraw类，但是！！！callDrawByType是私有方法呀，没办法重写的

**Comment by Dunqing** [comment]
你同步下最新代码 现在版本是0.4.1

**Comment by Dunqing** [comment]
适配了下

你同步下代码，应该能正常跑起来了

**Comment by chinbor** [comment]
.vscode文件也可以提交下，这样我可以使用你的保存自动格式化，马上补修复

**Comment by chinbor** [comment]
我怎么提pr给您呢，只是一个很小的修复
![image](https://user-images.githubusercontent.com/35005731/188675554-6d90d144-4120-4515-9709-6a83bf31457c.png)

**Comment by chinbor** [comment]
![image](https://user-images.githubusercontent.com/35005731/188675505-1ca32006-1e0f-4b6a-9a7c-1b36ee32da2c.png)
只是

**Comment by Dunqing** [comment]
在你fork的项目切个新分支后把你的修改在这个分支提交 然后来到这个项目上点pull request 一般情况下就会提示你可以创建PR了 如果没有你也可以手动创建
